apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deploy
spec:
  replicas: {{ .Values.replicas }} 
  selector:
    matchLabels:
      app: flaske-deploy
  strategy: {}
  template:
    metadata:
      labels:
        app: flaske-deploy
    spec:
      containers:
      - image: {{ .Values.image }}:{{ .Values.tag }}
        name: flaskex
        ports:
        - containerPort: 5000
