name: Terraform EKS Provisioning

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up AWS credentials (using GitHub Secrets)
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.9

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Apply Terraform configuration to provision the resources
      - name: Terraform Apply
        run: terraform apply -auto-approve

      # Output the EKS cluster name (optional)
      - name: Output EKS Cluster Name
        run: echo "EKS Cluster Name: my-cluster"
